In [3]:
import chart_studio.plotly as py
import plotly.graph_objs as go 
import pandas as pd
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

W: Number of wins
L: Number of losses
W/L%: Win-loss percentage, calculated as W / (W + L)
GB: Games behind the first place team in the conference
PS/G: Points scored per game
PA/G: Points allowed per game
SRS: Simple Rating System, a rating that takes into account average point differential and strength of schedule. A positive SRS indicates that a team is above average, and a negative SRS indicates that a team is below average.

In [4]:
df_east = pd.read_csv('eastern_conference.csv')
df_east

     Eastern Conference   W   L   W/L%    GB   PS/G   PA/G   SRS
0           Miami Heat*  53  29  0.646   0.0  110.0  105.6  4.23
1       Boston Celtics*  51  31  0.622   2.0  111.8  104.5  7.02
2      Milwaukee Bucks*  51  31  0.622   2.0  115.5  112.1  3.22
3   Philadelphia 76ers*  51  31  0.622   2.0  109.9  107.3  2.57
4      Toronto Raptors*  48  34  0.585   5.0  109.4  107.1  2.38
5        Chicago Bulls*  46  36  0.561   7.0  111.6  112.0 -0.38
6        Brooklyn Nets*  44  38  0.537   9.0  112.9  112.1  0.82
7   Cleveland Cavaliers  44  38  0.537   9.0  107.8  105.7  2.04
8        Atlanta Hawks*  43  39  0.524  10.0  113.9  112.4  1.55
9     Charlotte Hornets  43  39  0.524  10.0  115.3  114.9  0.53
10      New York Knicks  37  45  0.451  16.0  106.5  106.6 -0.01
11   Washington Wizards  35  47  0.427  18.0  108.6  112.0 -3.23
12       Indiana Pacers  25  57  0.305  28.0  111.5  114.9 -3.26
13      Detroit Pistons  23  59  0.280  30.0  104.8  112.5 -7.36
14        Orlando Magic  22  60  0.268  31.0  104.2  112.2 -7.67

In [8]:
df_west = pd.read_csv('western_conference.csv')
df_west

         Western Conference   W   L   W/L%    GB   PS/G   PA/G   SRS
0             Phoenix Suns*  64  18  0.780   0.0  114.8  107.3  6.94
1        Memphis Grizzlies*  56  26  0.683   8.0  115.6  109.9  5.37
2    Golden State Warriors*  53  29  0.646  11.0  111.0  105.5  5.52
3         Dallas Mavericks*  52  30  0.634  12.0  108.0  104.7  3.12
4                Utah Jazz*  49  33  0.598  15.0  113.6  107.6  5.67
5           Denver Nuggets*  48  34  0.585  16.0  112.7  110.4  2.16
6   Minnesota Timberwolves*  46  36  0.561  18.0  115.9  113.3  2.53
7      Los Angeles Clippers  42  40  0.512  22.0  108.4  108.4  0.09
8     New Orleans Pelicans*  36  46  0.439  28.0  109.3  110.3 -0.84
9         San Antonio Spurs  34  48  0.415  30.0  113.2  113.0  0.02
10       Los Angeles Lakers  33  49  0.402  31.0  112.1  115.1 -3.08
11         Sacramento Kings  30  52  0.366  34.0  110.3  115.8 -5.26
12   Portland Trail Blazers  27  55  0.329  37.0  106.2  115.1 -8.55
13    Oklahoma City Thunder  24  58  0.293  40.0  103.7  111.8 -7.90
14          Houston Rockets  20  62  0.244  44.0  109.7  118.2 -8.26

In [6]:
df_east.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Eastern Conference  15 non-null     object
 1   W                   15 non-null     int64
 2   L                   15 non-null     int64
 3   W/L%                15 non-null     float64
 4   GB                  15 non-null     float64
 5   PS/G                15 non-null     float64
 6   PA/G                15 non-null     float64
 7   SRS                 15 non-null     float64
dtypes: float64(5), int64(2), object(1)
memory usage: 1.1+ KB

In [7]:
df_west.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Western Conference  15 non-null     object
 1   W                   15 non-null     int64
 2   L                   15 non-null     int64
 3   W/L%                15 non-null     float64
 4   GB                  15 non-null     float64
 5   PS/G                15 non-null     float64
 6   PA/G                15 non-null     float64
 7   SRS                 15 non-null     float64
dtypes: float64(5), int64(2), object(1)
memory usage: 1.1+ KB